ONP_DON = 0
ONP_KATSU = 1
ONP_DON_DAI = 2
ONP_KATSU_DAI = 3

ONP_SHORT = 0, 3
#-----------------------------

ONP_SYOUSETSU_NORMAL = 4
ONP_SYOUSETSU_BUNKI = 5

ONP_SYOUSETSU = 4, 5
#-----------------------------

ONP_RENDA1 = 6
ONP_RENDA_DAI1 = 7
ONP_GEKI = 8
ONP_IMO = 9

ONP_LONG = 6, 9
#-----------------------------
ONP_RENDA2 = 10
ONP_RENDA3 = 11
ONP_RENDA_DAI2 = 12
ONP_RENDA_DAI3 = 13
ONP_END = 14
ONP_IMO_HIGH = 15

OPTION_SPD_2x = 1
OPTION_SPD_3x = 2
OPTION_SPD_4x = 3
OPTION_SPD_MASK = 3

OPTION_AUTO = 4
OPTION_AUTO_MASK = 4

OPTION_ONP_MIRROR = 8
OPTION_ONP_RANDOM = 16
OPTION_ONP_SRANDOM = 24
OPTION_ONP_MASK = 24